fixup readme
jaredhocutt/openshift4-deploy pull request #33
Opened 2020-05-19 21:04 UTC by johnsimcall

Collab via Google Meets with Jared

2020-05-20 00:44 UTC, jaredhocutt requested changes

2020-05-20 00:44 UTC, jaredhocutt commented on README.md
> +| `rhcos_ami`         | :heavy_check_mark: |         | The AMI ID for RHCOS.<br><br>If you are deploying into a commercial AWS region, the AMI ID can be found [here][rhcos_ami_ids]. Be sure the docum
Fix the table formatting on the end. The `|` on the end don't line up.

In VSCode, there is a `Format Document` option in the menu you get after pressing `Ctrl + Shift + P` that should do it for you.

2020-05-20 23:14 UTC, johnsimcall commented
It took me three tries, but I think I'm ready for your re-review:
try #1 failed because I pushed to the wrong branch (airgapped)
try #2 failed because I added "|---|--...--| to the bottom of the table to see if it would render better

2020-05-21 01:07 UTC, jaredhocutt approved these changes

2020-05-21 01:07 UTC, merged